name: 'Setup mold'
description: 'Install mold as the default linker'
inputs:
  mold-version:
    description: 'The mold version to download'
    default: latest
  make-default:
    description: 'Make mold the default linker'
    default: true
runs:
  using: composite
  steps:
    - run: |
        version=${{ inputs.mold-version }}
        test $version = latest && version=$(wget -q -O- https://api.github.com/repos/rui314/mold/releases/latest | jq -r .tag_name | sed 's/^v//'); true
        wget -q -O- https://github.com/rui314/mold/releases/download/v$version/mold-$version-$(uname -m)-linux.tar.gz | sudo tar -C /usr/local --strip-components=1 -xzf -
        test ${{ inputs.make-default }} = true && sudo ln -sf /usr/local/bin/mold $(realpath /usr/bin/ld); true
      shell: bash
